name: microlearning
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  logging: ^1.0.2
  logger: ^2.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_animations: ^5.0.2
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/login.png
    - assets/logo-ulilalbab.png