name: microlearning
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.3
  logging: ^1.0.2
  logger: ^2.4.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.2
  path: ^1.9.0
  provider: ^6.1.2
  foundation: ^0.0.5
  image_picker_web: ^4.0.0
  universal_io: ^2.2.2
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_animations: ^5.0.2
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/foto1.png
    - assets/foto2.png
    - assets/foto3.png
    - assets/foto4.png
    - assets/ASET-PPDB.png
    - assets/cropped-Brand-Logo-ua.png
    - assets/Logo-SDIT.jpg
    - assets/Logo-SMAIT.png
    - assets/Logo-SMPIT.png
    - assets/Logo-TK.png
    - assets/TPA_ua.png
    
